### PR TITLE
Fix Japanese translation

### PR DESCRIPTION
**Pull request by nao20010128nao**

### CODE REVIEW

**Comment by crossle** [comment]
Thank you, the merge conflicts. or you update the newest strings. and help us retranslate all strings.

**Comment by nao20010128nao** [comment]
Ok. I'll do it again.

**Comment by crossle** [comment]
Thank you very much.

**Comment by crossle** [comment]
@nao20010128nao please help us translate all Japanese strings, thank you

**Comment by crossle** [comment]
I have merged all your translation, please update and help check, thank you.

**Pull request closed without merging**
